/*
 * Copyright 2021 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.codelab.basics.ui.theme

import androidx.compose.ui.graphics.Color

val Navy = Color(0xFF073042)
val Blue = Color(0xFF4285F4)
val LightBlue = Color(0xFFD7EFFE)
val Chartreuse = Color(0xFFEFF7CF)

val purple200 = Color(0xFFBB86FC)
val purple500 = Color(0xFF6200EE)
val purple700 = Color(0xFF3700B3)
val teal200 = Color(0xFF03DAC5)
val cardCollapsedBackgroundColor = Color(0xFFFEFFFD)
val cardExpandedBackgroundColor = Color(0xFF94CADF)


/*val md_theme_light_primary = Color(0xFF825500)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDDB3)
val md_theme_light_onPrimaryContainer = Color(0xFF291800)
val md_theme_light_secondary = Color(0xFF6F5B40)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFBDEBC)
val md_theme_light_onSecondaryContainer = Color(0xFF271904)
val md_theme_light_tertiary = Color(0xFF51643F)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD4EABB)
val md_theme_light_onTertiaryContainer = Color(0xFF102004)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1F1B16)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1F1B16)
val md_theme_light_surfaceVariant = Color(0xFFF0E0CF)
val md_theme_light_onSurfaceVariant = Color(0xFF4F4539)
val md_theme_light_outline = Color(0xFF817567)
val md_theme_light_inverseOnSurface = Color(0xFFF9EFE7)
val md_theme_light_inverseSurface = Color(0xFF34302A)
val md_theme_light_inversePrimary = Color(0xFFFFB951)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF825500)
val md_theme_light_outlineVariant = Color(0xFFD3C4B4)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB951)
val md_theme_dark_onPrimary = Color(0xFF452B00)
val md_theme_dark_primaryContainer = Color(0xFF633F00)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDDB3)
val md_theme_dark_secondary = Color(0xFFDDC2A1)
val md_theme_dark_onSecondary = Color(0xFF3E2D16)
val md_theme_dark_secondaryContainer = Color(0xFF56442A)
val md_theme_dark_onSecondaryContainer = Color(0xFFFBDEBC)
val md_theme_dark_tertiary = Color(0xFFB8CEA1)
val md_theme_dark_onTertiary = Color(0xFF243515)
val md_theme_dark_tertiaryContainer = Color(0xFF3A4C2A)
val md_theme_dark_onTertiaryContainer = Color(0xFFD4EABB)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1F1B16)
val md_theme_dark_onBackground = Color(0xFFEAE1D9)
val md_theme_dark_surface = Color(0xFF1F1B16)
val md_theme_dark_onSurface = Color(0xFFEAE1D9)
val md_theme_dark_surfaceVariant = Color(0xFF4F4539)
val md_theme_dark_onSurfaceVariant = Color(0xFFD3C4B4)
val md_theme_dark_outline = Color(0xFF9C8F80)
val md_theme_dark_inverseOnSurface = Color(0xFF1F1B16)
val md_theme_dark_inverseSurface = Color(0xFFEAE1D9)
val md_theme_dark_inversePrimary = Color(0xFF825500)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB951)
val md_theme_dark_outlineVariant = Color(0xFF4F4539)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF825500)*/

//darkblue

val md_theme_light_primary = Color(0xFF00639A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFCDE5FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001D32)
val md_theme_light_secondary = Color(0xFF51606F)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD5E4F6)
val md_theme_light_onSecondaryContainer = Color(0xFF0E1D2A)
val md_theme_light_tertiary = Color(0xFF68587A)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFEEDBFF)
val md_theme_light_onTertiaryContainer = Color(0xFF221533)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFCFCFF)
val md_theme_light_onBackground = Color(0xFF1A1C1E)
val md_theme_light_surface = Color(0xFFFCFCFF)
val md_theme_light_onSurface = Color(0xFF1A1C1E)
val md_theme_light_surfaceVariant = Color(0xFFDEE3EB)
val md_theme_light_onSurfaceVariant = Color(0xFF42474E)
val md_theme_light_outline = Color(0xFF72777F)
val md_theme_light_inverseOnSurface = Color(0xFFF0F0F4)
val md_theme_light_inverseSurface = Color(0xFF2F3033)
val md_theme_light_inversePrimary = Color(0xFF95CCFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF00639A)
val md_theme_light_outlineVariant = Color(0xFFC2C7CF)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF95CCFF)
val md_theme_dark_onPrimary = Color(0xFF003352)
val md_theme_dark_primaryContainer = Color(0xFF004A75)
val md_theme_dark_onPrimaryContainer = Color(0xFFCDE5FF)
val md_theme_dark_secondary = Color(0xFFB9C8DA)
val md_theme_dark_onSecondary = Color(0xFF233240)
val md_theme_dark_secondaryContainer = Color(0xFF3A4857)
val md_theme_dark_onSecondaryContainer = Color(0xFFD5E4F6)
val md_theme_dark_tertiary = Color(0xFFD3BFE6)
val md_theme_dark_onTertiary = Color(0xFF382A49)
val md_theme_dark_tertiaryContainer = Color(0xFF4F4061)
val md_theme_dark_onTertiaryContainer = Color(0xFFEEDBFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C1E)
val md_theme_dark_onBackground = Color(0xFFE2E2E5)
val md_theme_dark_surface = Color(0xFF1A1C1E)
val md_theme_dark_onSurface = Color(0xFFE2E2E5)
val md_theme_dark_surfaceVariant = Color(0xFF42474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC2C7CF)
val md_theme_dark_outline = Color(0xFF8C9198)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C1E)
val md_theme_dark_inverseSurface = Color(0xFFE2E2E5)
val md_theme_dark_inversePrimary = Color(0xFF00639A)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF95CCFF)
val md_theme_dark_outlineVariant = Color(0xFF42474E)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF96CCFF)


val brownmd_theme_light_primary = Color(0xFFEBE4CD)
val brownmd_theme_light_onPrimary = Color(0xFFFFFFFF)
val brownmd_theme_light_primaryContainer = Color(0xFFF7E467)
val brownmd_theme_light_onPrimaryContainer = Color(0xFF201C00)
val brownmd_theme_light_secondary = Color(0xFF645F41)
val brownmd_theme_light_onSecondary = Color(0xFFFFFFFF)
val brownmd_theme_light_secondaryContainer = Color(0xFFEBE3BD)
val brownmd_theme_light_onSecondaryContainer = Color(0xFF1F1C05)
val brownmd_theme_light_tertiary = Color(0xFF416651)
val brownmd_theme_light_onTertiary = Color(0xFFFFFFFF)
val brownmd_theme_light_tertiaryContainer = Color(0xFFC3ECD1)
val brownmd_theme_light_onTertiaryContainer = Color(0xFF002112)
val brownmd_theme_light_error = Color(0xFFBA1A1A)
val brownmd_theme_light_errorContainer = Color(0xFFFFDAD6)
val brownmd_theme_light_onError = Color(0xFFFFFFFF)
val brownmd_theme_light_onErrorContainer = Color(0xFF410002)
val brownmd_theme_light_background = Color(0xFFF5E9C7)
val brownmd_theme_light_onBackground = Color(0xFF1D1C16)
val brownmd_theme_light_surface = Color(0xFFFFFBFF)
val brownmd_theme_light_onSurface = Color(0xFF1D1C16)
val brownmd_theme_light_surfaceVariant = Color(0xFFE8E2D0)
val brownmd_theme_light_onSurfaceVariant = Color(0xFF4A4739)
val brownmd_theme_light_outline = Color(0xFF7B7768)
val brownmd_theme_light_inverseOnSurface = Color(0xFFF5F0E7)
val brownmd_theme_light_inverseSurface = Color(0xFF32302A)
val brownmd_theme_light_inversePrimary = Color(0xFFDAC84E)
val brownmd_theme_light_shadow = Color(0xFF000000)
val brownmd_theme_light_surfaceTint = Color(0xFF6A5F00)
val brownmd_theme_light_outlineVariant = Color(0xFFCCC6B5)
val brownmd_theme_light_scrim = Color(0xFF000000)
//lightbrown


/*
val md_theme_light_primary = Color(0xFF6A5F00)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFF7E467)
val md_theme_light_onPrimaryContainer = Color(0xFF201C00)
val md_theme_light_secondary = Color(0xFF645F41)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFEBE3BD)
val md_theme_light_onSecondaryContainer = Color(0xFF1F1C05)
val md_theme_light_tertiary = Color(0xFF416651)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC3ECD1)
val md_theme_light_onTertiaryContainer = Color(0xFF002112)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF5E9C7)
val md_theme_light_onBackground = Color(0xFF1D1C16)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1D1C16)
val md_theme_light_surfaceVariant = Color(0xFFE8E2D0)
val md_theme_light_onSurfaceVariant = Color(0xFF4A4739)
val md_theme_light_outline = Color(0xFF7B7768)
val md_theme_light_inverseOnSurface = Color(0xFFF5F0E7)
val md_theme_light_inverseSurface = Color(0xFF32302A)
val md_theme_light_inversePrimary = Color(0xFFDAC84E)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF6A5F00)
val md_theme_light_outlineVariant = Color(0xFFCCC6B5)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFDAC84E)
val md_theme_dark_onPrimary = Color(0xFF373100)
val md_theme_dark_primaryContainer = Color(0xFF504700)
val md_theme_dark_onPrimaryContainer = Color(0xFFF7E467)
val md_theme_dark_secondary = Color(0xFFCFC7A2)
val md_theme_dark_onSecondary = Color(0xFF353117)
val md_theme_dark_secondaryContainer = Color(0xFF4C472B)
val md_theme_dark_onSecondaryContainer = Color(0xFFEBE3BD)
val md_theme_dark_tertiary = Color(0xFFA7D0B6)
val md_theme_dark_onTertiary = Color(0xFF113725)
val md_theme_dark_tertiaryContainer = Color(0xFF294E3A)
val md_theme_dark_onTertiaryContainer = Color(0xFFC3ECD1)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1D1C16)
val md_theme_dark_onBackground = Color(0xFFE7E2D9)
val md_theme_dark_surface = Color(0xFF1D1C16)
val md_theme_dark_onSurface = Color(0xFFE7E2D9)
val md_theme_dark_surfaceVariant = Color(0xFF4A4739)
val md_theme_dark_onSurfaceVariant = Color(0xFFCCC6B5)
val md_theme_dark_outline = Color(0xFF959181)
val md_theme_dark_inverseOnSurface = Color(0xFF1D1C16)
val md_theme_dark_inverseSurface = Color(0xFFE7E2D9)
val md_theme_dark_inversePrimary = Color(0xFF6A5F00)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFDAC84E)
val md_theme_dark_outlineVariant = Color(0xFF4A4739)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFFFF8E1)
*/

/*
val md_theme_light_primary = Color(0xFF6A5F00)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFF7E467)
val md_theme_light_onPrimaryContainer = Color(0xFF201C00)
val md_theme_light_secondary = Color(0xFF645F41)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFEBE3BD)
val md_theme_light_onSecondaryContainer = Color(0xFF1F1C05)
val md_theme_light_tertiary = Color(0xFF416651)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC3ECD1)
val md_theme_light_onTertiaryContainer = Color(0xFF002112)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF5E9C7)
val md_theme_light_onBackground = Color(0xFF1D1C16)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1D1C16)
val md_theme_light_surfaceVariant = Color(0xFFE8E2D0)
val md_theme_light_onSurfaceVariant = Color(0xFF4A4739)
val md_theme_light_outline = Color(0xFF7B7768)
val md_theme_light_inverseOnSurface = Color(0xFFF5F0E7)
val md_theme_light_inverseSurface = Color(0xFF32302A)
val md_theme_light_inversePrimary = Color(0xFFDAC84E)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF6A5F00)
val md_theme_light_outlineVariant = Color(0xFFCCC6B5)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFDAC84E)
val md_theme_dark_onPrimary = Color(0xFF373100)
val md_theme_dark_primaryContainer = Color(0xFF504700)
val md_theme_dark_onPrimaryContainer = Color(0xFFF7E467)
val md_theme_dark_secondary = Color(0xFFCFC7A2)
val md_theme_dark_onSecondary = Color(0xFF353117)
val md_theme_dark_secondaryContainer = Color(0xFF4C472B)
val md_theme_dark_onSecondaryContainer = Color(0xFFEBE3BD)
val md_theme_dark_tertiary = Color(0xFFA7D0B6)
val md_theme_dark_onTertiary = Color(0xFF113725)
val md_theme_dark_tertiaryContainer = Color(0xFF294E3A)
val md_theme_dark_onTertiaryContainer = Color(0xFFC3ECD1)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1D1C16)
val md_theme_dark_onBackground = Color(0xFFE7E2D9)
val md_theme_dark_surface = Color(0xFF1D1C16)
val md_theme_dark_onSurface = Color(0xFFE7E2D9)
val md_theme_dark_surfaceVariant = Color(0xFF4A4739)
val md_theme_dark_onSurfaceVariant = Color(0xFFCCC6B5)
val md_theme_dark_outline = Color(0xFF959181)
val md_theme_dark_inverseOnSurface = Color(0xFF1D1C16)
val md_theme_dark_inverseSurface = Color(0xFFE7E2D9)
val md_theme_dark_inversePrimary = Color(0xFF6A5F00)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFDAC84E)
val md_theme_dark_outlineVariant = Color(0xFF4A4739)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFFFF8E1)*/
