
package com.example.mushafconsolidated.Entities

//primaryKeys ={"translation_id","verse_id"}
class TopicCorpusExpandWbwPOJO constructor(
    var root_a: String,
    var surah: Int,
    var ayah: Int,
    var wordno: Int,
    var wordcount: Int,
    var translation: String,
    var araone: String,
    var aratwo: String,
    var arathree: String,
    var arafour: String,
    var arafive: String,
    var tagone: String,
    var tagtwo: String,
    var tagthree: String,
    var tagfour: String,
    var tagfive: String,
    var detailsone: String,
    var detailstwo: String,
    var detailsthree: String,
    var detailsfour: String,
    var detailsfive: String,
    var en: String,
    var bn: String,
    var `in`: String,
    var ur: String?,
    var qurantext: String?,
    var passage_no: Int ,
    var ar_irab_two: String? ,
    var tafsir_kathir: String?,
var id: Int ,
var en_transliteration: String? ,
var en_jalalayn: String? ,
var en_arberry: String? ,
var ur_jalalayn: String? ,
var ur_junagarhi: String? ,
)